---
title: "About"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Background
In recent years, journalists, policymakers, and academics have become increasingly worried about the implications of climate-induced water scarcity for international conflict. Approximately [1.2 billion people](https://www.un.org/waterforlifedecade/scarcity.shtml) worldwide live in areas that lack sufficient water to support their populations, and this number is expected to increase significantly under the stress of [climate change](https://blogs.ei.columbia.edu/2019/09/23/climate-change-impacts-water/). Some academics have suggested that countries will turn to violent conflict as they attempt to preserve precious water supplies. Others, led by [Elinor Ostrom](https://www.econlib.org/library/Enc/bios/Ostrom.html), who won the [Nobel Prize](https://www.nobelprize.org/prizes/economic-sciences/2009/ostrom/facts/) in Economics for her work in this area, have suggested that increased scarcity will drive states to cooperate with one another more, attemptint to collectively govern their shared resources. 

While many academics have conducted in-depth case studies of water governance in transboundary river basins—including the Jordan River, Nile River, and Indus River—few quantitative studies have attempted to establish causal inference about the effect of resource scarcity on water governance outcomes. This project aims to fill that research gap, applying new methods to existing datasets to analyze water governance outcomes over the past 200 years. In so doing, it seeks to answer the following question: Is water scarcity correlated with cooperation or conflict between states?

This project's GitHub repo lives [here](https://github.com/wyatthurt/gov1005-final-project).

### The Data
This project draws heavily on the following datasets from the Oregon State University [Program in Water Conflict Management and Transformation](https://transboundarywaters.science.oregonstate.edu/content/data-and-datasets):

* **International Freshwater Treaties Database:** A dataset of over 600 international, freshwater-related agreements, covering the years 1820 to 2007. This dataset provides detailed information on the topics covered by treaties, revisions to the treaties, and is coded by river basin, allowing me to connect it with other datasets from OSU (with a small amount of data wrangling). 
* **International Water Events Database:** A dataset of conflicts over water between 1948 and 2008, which provides information on the source of conflict, duration of conflict, and how resolution was achieved.
* **International River Basin Organization (Database):** A dataset of currently-extant international river basin organizations, coded by basin and countries involved, including level and type of collaboration, principal issue(s), date of creation, and a short description of the organization's activities.

This project also extensively draws on data from the [World Bank](https://data.worldbank.org), accessed using the [wbstats() package](https://cran.r-project.org/web/packages/wbstats/index.html) in R.

### Acknowledgements
This project conceptually builds on several of my previous and current research projects, completed under the supervision of Professor William Clark, Professor Rosie Bsheer, Dr. Michaela Thompson, and Dr. Alicia Harley. I am also grateful for the guidance provided David Kane and Alyssa Huberts as I learned the art of data science and developed this project.

### About Me
I am a third-year undergraduate at Harvard University, pursuing a joint degree in Environmental Science & Public Policy and Near Eastern Languages & Civilizations. My research (and upcoming senior thesis) focuses on mechanisms for improving the governance of transboundary natural resources in conflict zones. You can reach me at [wyatthurt@college.harvard.edu](mailto:wyatthurt@college.harvard.edu). 
