---
title: "Final Project Data"
author: "Wyatt Hurt"
date: "02/24/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Installing necessary packages.

library(gt)
library(readr)
library(janitor)
library(dplyr)
library(lubridate)
library(tidyverse)
library(naniar)
library(wbstats)
library(readxl)
```

```{r events, include=FALSE}
na_strings <- c("NA", "N.A.", "n/a", "?location", "?relvant", ".", " ")

# Data already in tidy format. 

events <- read_csv("events_raw.csv", 
    col_types = 
      # Why are dates reading in as NA?
      cols(DATE = col_date(format = "%m/%d/%Y"), 
      DOC_DATE = col_date(format = "%m/%d/%Y"))) %>%
  clean_names() %>%
  replace_with_na_all(condition = ~.x %in% na_strings) %>%
  select(!c(id, id1, event_master, doc_date))

# how will I join these tables? bccode, but what about dates?
# how to clean up column contents (formulas typed wrong, "n/a - text" in number columns, etc.)
# add comments with explanation of columns
# split up list of countries?

```

```{r organizations, include=FALSE}


organizations <- read_csv("organizations_raw.csv") %>%
  clean_names() %>%
  replace_with_na_all(condition = ~.x %in% na_strings)

# add comments with explanation of columns
# clean question mark characters out of observations
# recode yes/no as 1/0
# changed typed n/a, dots, blanks, etc to actual n/a
# split up type, list of countries

```

```{r treaties, include=FALSE}

treaties <- read_csv("treaties_raw.csv") %>%
  clean_names() %>%
  replace_with_na_all(condition = ~.x %in% na_strings) %>%
  select(!c(entry_id))

# add comments with explanation of columns
# need to rename/select columns
#clean question mark characters out of observations
# recode yes/no as 1/0
# changed typed n/a, dots, blanks, etc to actual n/a
# how to split out signatories, basin members

```

```{r stats, include=FALSE}

# User guide for wbstats() http://127.0.0.1:15723/library/wbstats/doc/Using_the_wbstats_package.html
pop <- wb(indicator = "SP.POP.TOTL", startdate = 1900, enddate = 2015) %>%
  select(code = iso3c, date, pop = value)

gdp <- wb(indicator = "NY.GDP.PCAP.CD", startdate = 1900, enddate = 2015) %>%
  select(code = iso3c, date, gdp = value)

trade_percent_gdp <- wb(indicator = "TG.VAL.TOTL.GD.ZS", startdate = 1900, enddate = 2015) %>%
  select(code = iso3c, date, trade_percent_gdp = value)

```

```{r join, include=FALSE}

joined <- treaties %>%
  full_join(organizations, by = "bccode", suffix = c("_treaties", "_orgs")) %>%
  full_join(events, by = c("bccode" = "bccode1"), suffix = c("_treaties/orgs", "_events"))

# bccode2 also transfered, so should be okay that only merging based on bccode 1
```
